grupotesseract/vestylle-webapi

app/Http/Controllers/API/PessoaAPIController.php, app/Models/Pessoa.php, app/Repositories/PessoaRepository.php
https://www.pivotaltracker.com/story/show/164717980
=> Feature/164717980 - Retornar token do Facebook após login

app/Http/Controllers/API/PessoaAPIController.php, app/Repositories/PessoaRepository.php
[Link MR](https://www.pivotaltracker.com/story/show/164138464)
- Se tiver CPF, tenta obter o vestylle_id e outras infos que nao pegamos no form
- Se obter da vestylle, faz as outras requisições para obter saldo de pontos. vencimento dos pontos e data e ultima compra.
=> #164138464 Pegando infos após login

app/Http/Controllers/API/PessoaAPIController.php
[Link Pivotal](https://www.pivotaltracker.com/story/show/164675442)
=> Obtendo infos da vestylle no patch de Pessoa

app/Models/Pessoa.php, database/migrations/2019_01_23_014554_create_pessoas_table.php
https://www.pivotaltracker.com/story/show/164622038
=> Feature/164622038 - Criação de coluna Genero e Data de Nascimento em Pessoas

database/factories/CupomFactory.php, database/factories/OfertaFactory.php, database/seeds/CupomSeeder.php, database/seeds/DatabaseSeeder.php, database/seeds/OfertaSeeder.php
[Cupons](https://prnt.sc/n20iq9)
[Ofertas](https://prnt.sc/n20ie7)
@evandrododo se quiser usar pra brincar no front já tá valendo! :fire:
=> 164838282 | seeders para ofertas e cupons

composer.json, composer.lock
Esse PR tem o selo "Code Review mais fácil do universo".
=> Pacote barryvdh/laravel-cors

app/Http/Controllers/CuponController.php, app/Models/Cupon.php, database/migrations/2019_03_17_215902_create_cupons_table.php, database/migrations/2019_03_23_160035_add_column_foto_caminho_cupons.php, resources/views/cupons/create.blade.php, resources/views/cupons/edit.blade.php, resources/views/cupons/fields.blade.php, resources/views/cupons/show_fields.blade.php, routes/web.php
[Link do Pivotal](https://www.pivotaltracker.com/story/show/164718297) 
----
[Print do teste de endpont sem oferta associada](https://prnt.sc/n1xgle)
[Print do teste de endpoint com oferta associada](https://prnt.sc/n1xg78)
=> 164718297 | API | Inclusão de coluna foto no CRUD de Cupons

app/Http/Requests/API/CreatePessoaAPIRequest.php, app/Http/Requests/API/UpdatePessoaAPIRequest.php, app/Models/Pessoa.php
https://www.pivotaltracker.com/story/show/164899721
Para testar:
1 - inserir uma pessoa 
2 - atualizar dados da pessoa - não deve dar erro
3 - inserir uma pessoa com mesmo email - deve dar erro
4 - atualizar dados da pessoa com um email ja existente - deve dar erro
=> Feature/164899721 - Regra de validação unique para coluna e-mail (POST e PATCH)

database/migrations/2019_01_23_014554_create_pessoas_table.php, database/seeds/PessoasTableSeeder.php
https://www.pivotaltracker.com/story/show/164900740
Para testar:
1. Incluir no .env `SEED_DADOS_PESSOA=false`
2. Rodar `docker-compose exec workspace php artisan config:clear` na pasta do laradock
3. Rodar ` docker-compose exec workspace php artisan migrate:fresh --seed` na pasta do laradock
4. Deve demorar, mas ele deve inserir as entidades pessoas com seus saldos, data ultima compra e data proximo vencimento. Dá pra ir acompanhando no tinker ou no adminer a inserção dos registros, caso nao queira esperar até acabar.
Essa variável no .env vai ser necessário, pq senao ninguem aguenta ficar esperando 10minutos o negócio seedar. Nesse caso, usaríamos apenas para apresentação na vestylle, no ambiente develop/stage.
=> Feature/164900740 - Seed de Pontos, Data Ultima Compra e Vencimentos

app/Http/Controllers/API/PessoaAPIController.php, app/Http/Controllers/PessoaController.php, app/Models/Cupon.php, app/Models/Pessoa.php, database/migrations/2019_03_23_225604_add_column_cupom_primeiro_login_cupons.php, resources/views/cupons/fields.blade.php, resources/views/cupons/show_fields.blade.php
[Link do Pivotal](https://www.pivotaltracker.com/story/show/164599981)
=> 164599981 | API | Cadastrar cupom ao cliente após primeiro login

app/DataTables/CuponDataTable.php, app/DataTables/OfertaDataTable.php, app/Models/Cupon.php, app/Models/Oferta.php, database/factories/CupomFactory.php, database/factories/OfertaFactory.php, database/migrations/2019_04_03_040003_add_column_titulo_subtitulo_preco_ofertas.php, database/migrations/2019_04_03_040106_add_column_titulo_subtitulo_cupons.php, resources/views/cupons/fields.blade.php, resources/views/cupons/show_fields.blade.php, resources/views/ofertas/fields.blade.php, resources/views/ofertas/show_fields.blade.php
[Link do Pivotal](https://www.pivotaltracker.com/story/show/164844533)
[Vídeo de teste](https://www.useloom.com/share/0359601166a746b29ef618f0a239b57d?focus_title=1&muted=1)
----
**TODO**: Discutir a necessidade de implementar máscara de valor no backend para o preço da oferta. Do front pode mandar um número sem se preocupar com formatação em reais (ex: 123.99, '12.99', etc) que o mutator vai retornar o preço como '123,99', '12,99'. CC: @evandrododo
=> 164844533 | API | WebAadmin | Criação de colunas em Cupons/Ofertas

app/DataTables/Scopes/PessoasPorCupon.php, app/Http/Controllers/CuponController.php, app/Http/Controllers/OfertaController.php, resources/views/cupons/show.blade.php
[Link Pivotal](https://www.pivotaltracker.com/story/show/164622134)
Incluindo:
- `App\DataTables\Scopes\PessoasPorCupon` pra filtrar as Pessoas
- Alterando CuponController para incluir a DataTable de pessoas
- `php artisan tinker`
- `Pessoa::first()->attach(1);`
- Acessar `/cupons/1`
GGWP :+1:
=> Listagem de pessoas no show de cupons

.env.example, .gitignore, app/Http/Controllers/API/PessoaAPIController.php, app/Models/Oferta.php, app/Models/Pessoa.php, app/Repositories/PessoaRepository.php, routes/api.php, yarn.lock
https://www.pivotaltracker.com/story/show/165121998
Para testar:
- Acessar rota POST `http://localhost/api/login/facebook` com os parâmetros abaixo, que seria gerados pelo Facebook após autenticação pelo front (PWA ou Nativo)
```
email:fernandola@gmail.com
social_token:hahahaahaha
nome:Fernandola
```
=> Feature/165121998 - Alteração da rota do Facebook pra registrar token a partir do Token gerado pelo PWA/Nativo

database/factories/LojaFactory.php, database/seeds/DatabaseSeeder.php, database/seeds/LojaSeeder.php, resources/views/lojas/fields.blade.php
[https://www.pivotaltracker.com/n/projects/2227773/stories/165137255](https://www.pivotaltracker.com/n/projects/2227773/stories/165137255)
- Textarea em whatsapp e horario_funcionamento.
- Factory e Seed de Loja.
=> seed, factory de lojas

app/Http/Controllers/CuponController.php, resources/views/cupons/fields.blade.php
[Link do pivotal](https://www.pivotaltracker.com/story/show/165109660)
[Vídeo com fluxo de testes no WebAdmin](https://www.useloom.com/share/0255fe89893642ffbf4a0b616ca69064)
No `cuponApiController` acho que não precisa alterar pq o checkbox
feito no front certamente enviará true,false,1 ou 0. O checkbox do
laravel que é cagadão e manda um 'on' no lugar de valores true
e em casos de false nem seta a variável no request.
=> 165109660 | WebAdmin | Checkbox "Cupom primeiro login" não reflete valor do banco

app/Repositories/PessoaRepository.php, database/seeds/PessoasTableSeeder.php
[Link Pivotal](https://www.pivotaltracker.com/story/show/165300417)
=> Bugfix - Espacos quebrando o unique do email de Pessoa

app/Http/Controllers/API/OfertaAPIController.php, app/Models/Oferta.php
https://www.pivotaltracker.com/story/show/165601609
Para testar: acessar as rotas de /ofertas (listagem) e /ofertas/{id} (detalhamento) e verificar se os objetos de cupons estao associados
=> Feature/165601609 - Incluir objeto de cupom junto a Oferta na listagem e detalhamento

app/Http/Controllers/API/PessoaAPIController.php, app/Repositories/PessoaRepository.php
https://www.pivotaltracker.com/story/show/165541682
=> Feature/165541682 - Não permitir login no Facebook caso front não envie nenhum parâmetro

app/Helpers/VestylleDBHelper.php, app/Repositories/PessoaRepository.php
https://www.pivotaltracker.com/story/show/165600405
Foi incluído um método pra identificar Pessoas que tiveram saldo de pontos atualizados/cancelados/criados mas não fizeram nenhuma compra!
=> Feature/165600405 - Mudar regra de atualização de saldo de Pontos

app/DataTables/CuponDataTable.php, app/DataTables/FaleConoscoDataTable.php, app/DataTables/LojaDataTable.php, app/DataTables/OfertaDataTable.php, app/DataTables/PessoaDataTable.php, resources/views/cupons/fields.blade.php, resources/views/cupons/show.blade.php, resources/views/cupons/show_fields.blade.php, resources/views/fale_conoscos/fields.blade.php, resources/views/fale_conoscos/show_fields.blade.php, resources/views/layouts/menu.blade.php, resources/views/lojas/show_fields.blade.php, resources/views/ofertas/fields.blade.php, resources/views/ofertas/show.blade.php, resources/views/ofertas/show_fields.blade.php, resources/views/pessoas/fields.blade.php, resources/views/pessoas/index.blade.php, resources/views/pessoas/show_fields.blade.php, routes/web.php
[https://www.pivotaltracker.com/n/projects/2227773/stories/165734835](https://www.pivotaltracker.com/n/projects/2227773/stories/165734835)
Fix geral de estilo, rotas, tradução e número de colunas.
=> 165734835 webadmin ajustes

app/Http/Controllers/API/CuponAPIController.php, app/Http/Controllers/API/PessoaAPIController.php, app/Http/Controllers/CuponController.php, app/Http/Controllers/PessoaController.php, app/Models/Cupon.php, app/Models/CuponPessoa.php, app/Models/Pessoa.php, database/migrations/2019_05_09_005844_add_column_codigo_unico_cupon_pessoa.php, database/migrations/2019_05_13_221942_drop_column_cupom_primeiro_login_cupons.php, resources/views/cupons/fields.blade.php, resources/views/cupons/show_fields.blade.php, routes/api.php
- Sincronizar o Postman e bater na rota `cupons/{id_cupon}/ativar` (Cupons > Ativar)
=> 165824712 | API | Rota para Ativação do Cupom

app/Console/Commands/AtualizaPessoasDataUltimaCompra.php, app/Helpers/VestylleDBHelper.php, app/Http/Controllers/API/PessoaAPIController.php, app/Repositories/PessoaRepository.php, database/seeds/CategoriasTableSeeder.php, database/seeds/DatabaseSeeder.php, database/seeds/PessoasTableSeeder.php
https://www.pivotaltracker.com/story/show/165600854
**Para testar**
1 - Rodar `migrate:fresh --seed` - o seed foi alterado pra, por padrão, trazer as informações das pessoas da base da vestylle
2 - Rodar comando do artisan que atualiza pessoa - incluí uma rotina lá pra atualizar as categorias também. Achei melhor não fazer checagem por timestamp, e sim, trazer sempre tudo de uma vez, e na sequencia, atualizar os segmentos de todas as pessoas de nossa base
3 - Acessar tabela `segmentacoes`, e verificar algum `owner_id` referente ao model Pessoa que possua categoria associada. Em seguida, no tinker, rodar:
`$categorias = Pessoa::find({id_pessoa})->segmentacoes()->pluck('categoria_id')`
O método acima deve retornar um array de categorias associadas a essa pessoa. 
Futuramente, esse array …
=> Feature/165600854 - Métodos para atualização/inserção dos Tipos de Informação

app/Http/Controllers/API/PessoaAPIController.php, routes/api.php
A rota já foi adicionada à collecion do projeto no Postman
=> feature/165826035 | rota pra listagem de cupons utilizados

app/DataTables/LojaDataTable.php, app/Http/Controllers/API/LojaAPIController.php, app/Http/Controllers/CuponController.php, app/Http/Controllers/LojaController.php, app/Models/Loja.php, resources/views/lojas/create.blade.php, resources/views/lojas/edit.blade.php, resources/views/lojas/fields.blade.php, resources/views/lojas/index.blade.php, resources/views/lojas/show_fields.blade.php
=> 164844313 | Upload de múltiplas fotos para loja

app/Http/Controllers/API/CuponAPIController.php, app/Http/Controllers/API/LojaAPIController.php, app/Http/Controllers/API/OfertaAPIController.php
=> feature/166045096 | API | Incluir multiplas fotos no retorno de Ofertas/Cupons/Loja

app/Http/Controllers/CuponController.php, app/Http/Controllers/OfertaController.php, app/Models/Categoria.php, app/Models/Oferta.php, app/Models/Segmentacao.php, app/Providers/AppServiceProvider.php, app/Repositories/CategoriaRepository.php, app/ViewComposers/CategoriaComposer.php, public/mix-manifest.json, resources/js/app.js, resources/js/categorias.js, resources/sass/custom.scss, resources/sass/select2.scss, resources/views/categorias/partials/select.blade.php, resources/views/cupons/fields.blade.php, resources/views/cupons/show_fields.blade.php, resources/views/layouts/app.blade.php, resources/views/ofertas/fields.blade.php, resources/views/ofertas/show_fields.blade.php, webpack.mix.js
Principais mods:
- Acessores em Categoria
- `CategoriaRepository` com o metodo `getCategoriasSelect` - usado para inserir as categorias possiveis na blade de categorias.
- `CategoriaComposer` - É um ViewComposer que injeta a variavel `$categorias` na blade `categorias.partials.select`
- Blade contendo o input field para selecioanar as categorias
=> Feature/#166016516 - Atrelar Categorias á Cupons/Ofertas/Pessoas..

app/Http/Controllers/API/CuponAPIController.php, app/Http/Controllers/QRCodeController.php, app/Models/Cupon.php, app/Repositories/CuponRepository.php, database/migrations/2019_03_17_215902_create_cupons_table.php
https://www.pivotaltracker.com/story/show/166122871
=> Feature/166122871 - Limitar tamanho do hash do Cupom

app/Http/Controllers/CuponController.php, app/Http/Controllers/OfertaController.php
[Link Pivotal](https://www.pivotaltracker.com/story/show/166190183)
Corrige o problema de não ser possivel remover todas as categorias de uma Oferta ou Cupon.
-----
**PS:** Ticket Stagefix, necessario mergear na develop também.
=> Stagefix | #166190183 | Remover Categorias de uma Oferta ou Cupon

app/Repositories/CuponRepository.php
https://www.pivotaltracker.com/story/show/166248650
=> Bugfix/166248650 - Segmentação de cupons parou de funcionar após filtro de utilizado venda

.env.example, .env.example-vessel, app/Http/Controllers/API/FaleConoscoAPIController.php, app/Mail/FaleConoscoCreated.php, app/Models/FaleConosco.php, resources/views/emails/fale-conosco-created.blade.php, routes/api.php
[Link Pivotal](https://www.pivotaltracker.com/story/show/166043002)
-----
**PS:**  Parte do problema era a config 'MAIL_DRIVER' do .env. Já Alterei para as configs certas nos servidores.
**PS2:** Pra testar local, precisa alterar o 'MAIL_DRIVER' pra `log` e inserir `EMAIL_DESTINO_CONTATO` e `EMAIL_ORIGEM_CONTATO` para endereços de email validos. (Não precisa ser um e-mail real)
=> Alternado Controller / Mail. Resolve o erro 500 do fale conosco

app/Repositories/OfertaRepository.php
Incluindo Cupons associados a Ofertas na listagem de Ofertas da API.
-----
*PS:* Stagefix, tirei da stage e a MR está pra stage. Mas precisa também mergear a branch na develop.
=> Incluindo cupons da oferta na listagem de ofertas da API

app/Http/Controllers/API/CuponAPIController.php, app/Http/Controllers/API/OfertaAPIController.php, app/Http/Controllers/CuponController.php, app/Http/Controllers/OfertaController.php, app/Models/Cupon.php, app/Models/Oferta.php, resources/js/components/VueImageSlider.vue
Links no pivotal:
- https://www.pivotaltracker.com/story/show/166276184
- https://www.pivotaltracker.com/story/show/166049855
Com essas changes o comportamento ainda não fica 100% pq depende de timeout e do tempo de resposta do cloudinary, então ainda pode ficar meio zuadinho por causa dos reloads inseridos. Mas já melhora um tanto a UX pra essas duas situações.
=> 166049855 | WebAdmin | Remoção /Add Multiplas Fotos + Ajustes de comportamento ao subir imagens

app/Http/Controllers/CuponController.php, resources/views/cupons/fields.blade.php
https://www.pivotaltracker.com/story/show/166339033
=> Feature/166339033 - Correção do select de ofertas no create de cupons

app/Http/Controllers/API/CuponAPIController.php, app/Models/Cupon.php
https://www.pivotaltracker.com/story/show/166353753
=> Feature/166353753 - Enviar objeto inteiro de pessoa associada a um cupom

app/Providers/AppServiceProvider.php, app/Providers/ViewServiceProvider.php, config/app.php, database/seeds/CategoriasTableSeeder.php, database/seeds/PessoasTableSeeder.php
https://www.pivotaltracker.com/story/show/166353865
=> Bugfix/166353865 - Bug referente ao boot do Laravel - ViewComposer de Categorias

app/Models/Campanha.php, app/Repositories/CampanhaRepository.php, database/migrations/2019_06_06_221120_create_campanhas_table.php, resources/sass/admin-custom.scss, resources/sass/app.scss, resources/views/campanhas/fields.blade.php, resources/views/campanhas/partials/segmentar-diaaniversario.blade.php, resources/views/campanhas/partials/segmentar-mesaniversario.blade.php, resources/views/campanhas/partials/segmentar-saldopontos.blade.php, resources/views/campanhas/partials/segmentar-ultimacompra.blade.php, resources/views/campanhas/partials/segmentar-vencimentopontos.blade.php, resources/views/layouts/app.blade.php, routes/web.php
[Link Pivotal](https://www.pivotaltracker.com/story/show/166674023)
- Incluindo segmentacao por dia do aniversário (migration, model, controller, repositorio)
- Ajustes no frontend do crud de campanhas
=> Webadmin | API| Incluir Segmentação por 'dia-aniversario' CRUD Campanhas

app/Console/Commands/AtualizaPessoasSemIDVestylle.php, app/Console/Kernel.php, app/Repositories/PessoaRepository.php
[Link do Pivotal](https://www.pivotaltracker.com/story/show/166166906)
----
- Estar com Pessoas na base:  `php artisan migrate:fresh --seed`
- Entrar no tinker
- Pegar o cpf de alguem que tenha id_vestylle:  `Pessoa::whereNotNull('id_vestylle')->pluck('cpf', 'id')`
- ForceDelete em uma dessas Pessoas: `Pessoa::find( ID_X )->forceDelete()`
- Criar outra pessoa com o mesmo CPF (pelo tinker) `Pessoa::create(['cpf' => ' CPF_X '])`
- Sair do tinker
- Rodar `php artisan vestylle:atualiza-clientes-novos`
- Voltar no tinker e ver se a pessoa recem criada foi atualizada: `Pessoa::latest()->first()`
=> #166166906 Rotina para atualizar pessoas que estão sem id_vestylle

app/Http/Controllers/API/CuponAPIController.php, app/Http/Controllers/CuponController.php, app/Http/Controllers/QRCodeController.php, app/Http/Requests/CreateCuponRequest.php, app/Http/Requests/UpdateCuponRequest.php, app/Models/Cupon.php, app/Repositories/CuponRepository.php, database/migrations/2019_03_17_215902_create_cupons_table.php, resources/views/cupons/fields.blade.php, resources/views/cupons/show_fields.blade.php
[Link Pivotal](https://www.pivotaltracker.com/story/show/166723047)
----------
- Adicionando campo codigo_amigavel na tabela, fields, model..
- Alterando validação no `store` e `updade` de `CuponController`, para usar as `FormRequests`, e validar dinamicamente a regra unique.
- Alterando endpoint da API, `showEncryptado` para buscar também pelo codigo_amigavel antes de retornar false.
=> Feature/166723047- código amigavel para ativacao do cupom

app/DataTables/Scopes/PessoasPorCampanha.php, app/Http/Controllers/CampanhaController.php, resources/views/campanhas/show.blade.php, resources/views/campanhas/show_fields.blade.php, resources/views/cupons/show.blade.php
[Link do Pivotal](https://www.pivotaltracker.com/story/show/167106622)
----
- Alterando show_fields de campanha pra só mostrar os campos quando tiver valor
- Incluindo datatable de pessoas no show de campanhas
- Criando datatable scope PessoasPorCampanha, para pegar as pessoas a partir da campanha.
:+1:
=> #167106622 - Listagem das pessoas afetadas pela campanha

resources/views/pessoas/show_fields.blade.php
[Link Pivotal](https://www.pivotaltracker.com/story/show/167097538)
----
- Ajustes no show_fields de Pessoa pra listar as categorias (e só mostrar os campos que tiverem valor)
:+1:
=> #167097538 Listagem das categorias da pessoa

app/Http/Controllers/PessoaController.php, app/Models/Pessoa.php, database/migrations/2019_07_07_005633_remove_soft_delete.php, routes/web.php
- Basicamente remove o softDeletes e apliquei os deletes secundários no destrou do controller.
- Protegendo rota de notificação
https://www.pivotaltracker.com/story/show/167096015
https://www.pivotaltracker.com/story/show/167017989
=> Bugfix/167096015 - Tratamentos quando usuário é excluído no Painel Administrativo

app/DataTables/Scopes/PessoasPorCampanha.php
Sem ticket do pivotal.
Trocando a query da scope PessoasPorCampanha por um whereIn nos Ids das pessoas elegiveis.
=> Fix na scope da datatable PessoasPorCampanha

app/Mail/FaleConoscoCreated.php, app/Models/FaleConosco.php, database/migrations/2019_07_13_014420_add_nome_fale_conosco.php, resources/views/emails/fale-conosco-created.blade.php
[Link Pivotal](https://www.pivotaltracker.com/story/show/167140332)
----
- Incluindo migration / fillable para o campo 'nome' no model `FaleConosco`
- Incluindo assunto no email
=> Bugfix/167140332 Fale Conosco

app/Http/Controllers/Auth/ResetPasswordController.php, app/Http/Controllers/PessoaController.php, app/Notifications/ResetPassword.php, resources/views/auth/passwords/reset.blade.php, resources/views/auth/passwords/reset_success.blade.php, routes/web.php
https://www.pivotaltracker.com/story/show/167292095
- Aplicando CSS no form de reset
- Criando nova view de Sucesso após reset
- Ajustando Notification pro remetente ser da Vestylle (estava Example antes)
**Para testar:** 
- Acessar rota no Postman (Forgot Password) passando no body algum email valido, e verificar email enviado no laravel.log. 
- Acessar link enviado no email, redefinir nova senha e efetuar login com nova senha. 
**CUIDADO PRA NAO TESTAR COM ALGUM USUARIO REAL DA VESTYLLE E ESQUECER DE MUDAR O MAIL DRIVER, E ENVIAR EMAILS REAIS PRA ESSAS PESSOAS.**
=> Feature/167292095 - Ajustes em Esqueci minha Senha

database/migrations/2019_07_26_134151_remove_unique_endpoint_pessoa_push.php
https://www.pivotaltracker.com/story/show/167516556
=> Bugfix/167516556 - Removendo constraint unique na tabela pessoas_push

app/Http/Controllers/LojaController.php, resources/views/lojas/show_fields.blade.php
https://www.pivotaltracker.com/story/show/167516427
Para testar
1 - Atualizar campos da loja e visualizar o show e o retorno da API
=> Bugfix/167516427 - Não está salvando Whatsapp2 em Loja

app/Http/Controllers/API/CuponAPIController.php, app/Http/Requests/API/CreatePessoaAPIRequest.php, app/Models/Cupon.php, app/Models/CuponPessoa.php, app/Rules/CPFValido.php, database/migrations/2019_07_30_165753_add_column_dataexpiracao_cupons_pessoas.php
https://www.pivotaltracker.com/story/show/167463514
=> Feature/167463514 - Aplicar condição da data de validade nos cupons ativos

app/Http/Controllers/API/PessoaAPIController.php, app/Models/Cupon.php, app/Repositories/CuponRepository.php
[Link Pivotal](https://www.pivotaltracker.com/story/show/167633146)
-----
=> Feature/167633146 - Removendo Cupons expirados das respostas da API

resources/js/components/VueImageSlider.vue, resources/js/components/VueUploadMultipleImage.vue
[Link Pivotal](https://www.pivotaltracker.com/story/show/167858955)
Incluindo sweetalert para confirmar.
=> #167858955 UX Delete de fotos Cupom e Oferta

app/Http/Controllers/CuponController.php, resources/views/cupons/fields.blade.php
[Link Pivotal](https://www.pivotaltracker.com/story/show/167944477)
=> Corrigindo checkbox Aparece em 'Meus Cupoms'

app/Http/Controllers/API/CuponAPIController.php, app/Http/Controllers/API/PessoaAPIController.php
[Link Pivotal](https://www.pivotaltracker.com/story/show/167944436)
----
Foi alterado só nos endpoints:
- /pessoas/{id}/cupons
- /cupons/{id}
=> Trocando data_validade do cupom pela data_expiracao da tabela pivô

app/Http/Controllers/API/SubscriptionAPIController.php, app/Http/Controllers/QRCodeController.php
[Link Pivotal](https://www.pivotaltracker.com/story/show/168556599)
----
- Validação se existem pessoas no resultado da segmentação de uma campanha, antes de disparar a push
- Limpando nome do cupom antes de gerar a imagem do QRCode.
:+1:
=> 168556599 bufix ajustes webadmin

app/Http/Controllers/API/PessoaAPIController.php, app/Http/Requests/API/UpdatePessoaAPIRequest.php
[Link Pivotal](https://www.pivotaltracker.com/story/show/169140691)
----
- Incluindo regra date_format
- Incluindo método messages para retornar uma mensagem amigável
- Incluindo IF para não obter a data_nascimento caso a pessoa já tenha informado no update
---
PS: branch tirada da master e voltando para a master. (necessário parear com develop e stage)
=> Hotfix | Incluindo validação para o campo data_nascimento em Pessoa

app/DataTables/PessoaDataTable.php, app/DataTables/PessoasQuePermitiramPushDataTable.php, app/Http/Controllers/PessoaController.php, app/Models/Pessoa.php, resources/sass/admin-custom.scss, resources/views/layouts/menu.blade.php, resources/views/pessoas/show_fields.blade.php, resources/views/pessoas/show_notificacoes.blade.php, resources/views/welcome.blade.php, routes/web.php
[Link Pivotal](https://www.pivotaltracker.com/story/show/169654425)
----
- Incluindo coluna 'Permitiu Notificações' na datatable de Pessoas
- Incluindo dropdown no menu 'Pessoas' para selecionar entre 'Todas' e 'Que permitiram notificações'
- Incluindo métodos em `Pessoa` para determinar se ela permitiu ou não as notificações
- Incluindo nova Datatable para filtrar os ids das pessoas que serão listadas
=> 169654425 listagem pessoas notificacoes
